# Pre-commit configuration for code quality checks - specific to AE/backend_v2 project
# See https://pre-commit.com/ for more information

# This configuration defines project-specific paths
default_install_hook_types: [pre-commit, commit-msg]
default_stages: [commit]

# Only run hooks on files in the AE/backend_v2 directory
files: ^AE/backend_v2/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=1000']

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "88"]
        files: ^AE/backend_v2/.*\.py$

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length", "88"]
        files: ^AE/backend_v2/.*\.py$

  - repo: https://github.com/pycqa/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args:
          - "--remove-all-unused-imports"
          - "--remove-unused-variables"
          - "--in-place"
          - "--recursive"
          - "--ignore-init-module-imports"
        files: ^AE/backend_v2/.*\.py$
